default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: coach-app_development

test:
  <<: *default
  database: coach-app_test

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: d176n5ctcsng7
  username: btmaeepeijucjr
  password: <%= ENV['COACH-WEBAPP_DATABASE_PASSWORD'] %>
