# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75bcfd225bb60003d696d9db3886c1e56d8129372a49995a024520d4af15595badab8bdb3b0cc0550642956c742b68e43c211cbd489d92db2fed9ab4e898d446

test:
  secret_key_base: 2f432b9bc9af8e6f92e6e1a6d9c9791a4942717ab206e1a2c6e8c865e24507de43e12ba4be1073cdce2f9b427dd2763b076f59af32adfb3d5c0260f56de2ff0b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
